### PR TITLE
docs(README): fix readme for some flags in cli

### PR DESCRIPTION
**Pull request by bnjjj**

### CODE REVIEW

**Comment by STRML** [comment]
Thanks for the fix!

In retrospect it's somewhat confusing that the package is `graylog-cli-dashboard` but the entry script is `graylog-dashboard`. I'll likely fix that in the next major.

**Comment by STRML** [comment]
Once you sign the CLA I'll merge this in.

**Comment by bnjjj** [comment]
Done :)

**Comment by STRML** [comment]
🎉

**Pull request merged**
